### PR TITLE
Implemented attendee management

### PR DESCRIPTION
**Pull request by stanislavkhatko**

### CODE REVIEW

**Comment by stanislavkhatko** [comment]
Admin should receive email when someone attends the event. Attendee receives the email when it's status or role is updated ( don't checking for raw data though so every 'update' click triggers the email)

**Comment by stanislavkhatko** [comment]
Also list of attendee statuses and roles isn't full. Cropped to display only those in play

**Comment by stanislavkhatko** [comment]
@tompscanlan Had issues with event-attendee.service.spec, there are many tests, some I broke with methods update, I'd finally refactor it and move mocks away from the file...

**Comment by tompscanlan** [comment]
Skip the tests for now. I'll add them back as I go.

**Review by tompscanlan — APPROVED** [review]

**Pull request merged**
